In [99]:
import numpy as np
import pandas as pd
import matplotlib as mp
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [100]:
df = pd.read_csv('https://archive.ics.uci.edu/static/public/911/data.csv')

df.head()

,num_records,recipe_number,recipe_code,recipe_name,comment_id,user_id,user_name,user_reputation,created_at,reply_count,thumbs_up,thumbs_down,stars,best_score,text
0,0,1,14299,Creamy White Chili,sp_aUSaElGf_14299_c_2G3aneMRgRMZwXqIHmSdXSG1hEM,u_9iFLIhMa8QaG,Jeri326,1,1665619889,0,0,0,5,527,"I tweaked it a little, removed onions because ..."
1,1,1,14299,Creamy White Chili,sp_aUSaElGf_14299_c_2FsPC83HtzCsQAtOxlbL6RcaPbY,u_Lu6p25tmE77j,Mark467,50,1665277687,0,7,0,5,724,Bush used to have a white chili bean and it ma...
2,2,1,14299,Creamy White Chili,sp_aUSaElGf_14299_c_2FPrSGyTv7PQkZq37j92r9mYGkP,u_s0LwgpZ8Jsqq,Barbara566,10,1664404557,0,3,0,5,710,I have a very complicated white chicken chili ...
3,3,1,14299,Creamy White Chili,sp_aUSaElGf_14299_c_2DzdSIgV9qNiuBaLoZ7JQaartoC,u_fqrybAdYjgjG,jeansch123,1,1661787808,2,2,0,0,581,"In your introduction, you mentioned cream chee..."
4,4,1,14299,Creamy White Chili,sp_aUSaElGf_14299_c_2DtZJuRQYeTFwXBoZRfRhBPEXjI,u_XXWKwVhKZD69,camper77,10,1664913823,1,7,0,0,820,Wonderful! I made this for a &#34;Chili/Stew&#...

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18182 entries, 0 to 18181
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   num_records      18182 non-null  int64
 1   recipe_number    18182 non-null  int64
 2   recipe_code      18182 non-null  int64
 3   recipe_name      18182 non-null  object
 4   comment_id       18182 non-null  object
 5   user_id          18182 non-null  object
 6   user_name        18182 non-null  object
 7   user_reputation  18182 non-null  int64
 8   created_at       18182 non-null  int64
 9   reply_count      18182 non-null  int64
 10  thumbs_up        18182 non-null  int64
 11  thumbs_down      18182 non-null  int64
 12  stars            18182 non-null  int64
 13  best_score       18182 non-null  int64
 14  text             18180 non-null  object
dtypes: int64(10), object(5)
memory usage: 2.1+ MB

In [102]:
df.describe()

,num_records,recipe_number,recipe_code,user_reputation,created_at,reply_count,thumbs_up,thumbs_down,stars,best_score
count,18182.000000,18182.000000,18182.000000,18182.000000,1.818200e+04,18182.000000,18182.000000,18182.000000,18182.000000,18182.000000
mean,121.465295,38.689363,21773.667253,2.159608,1.623710e+09,0.014630,1.089264,0.549335,4.288802,153.162138
std,116.747893,29.786647,23965.109637,10.014666,5.468697e+06,0.137974,4.201004,3.470124,1.544786,141.075316
min,0.000000,1.000000,386.000000,0.000000,1.613035e+09,0.000000,0.000000,0.000000,0.000000,0.000000
25%,45.000000,12.000000,6086.000000,1.000000,1.622717e+09,0.000000,0.000000,0.000000,5.000000,100.000000
50%,91.000000,33.000000,14600.000000,1.000000,1.622718e+09,0.000000,0.000000,0.000000,5.000000,100.000000
75%,150.000000,64.000000,33121.000000,1.000000,1.622718e+09,0.000000,0.000000,0.000000,5.000000,100.000000
max,724.000000,100.000000,191775.000000,520.000000,1.665756e+09,3.000000,106.000000,126.000000,5.000000,946.000000

In [103]:
columns_to_keep = [
    'recipe_number','recipe_code' ,'recipe_name', 'user_name' ,'user_reputation', 'reply_count',
    'thumbs_up', 'thumbs_down', 'stars', 'best_score' ,'text'
]

dataset_cleaned = df[columns_to_keep]

# Handling missing values: Drop rows with missing values in critical columns
critical_columns = ['stars', 'text']
data = dataset_cleaned.dropna(subset=critical_columns)

In [104]:
dataset_cleaned

,recipe_number,recipe_code,recipe_name,user_name,user_reputation,reply_count,thumbs_up,thumbs_down,stars,best_score,text
0,1,14299,Creamy White Chili,Jeri326,1,0,0,0,5,527,"I tweaked it a little, removed onions because ..."
1,1,14299,Creamy White Chili,Mark467,50,0,7,0,5,724,Bush used to have a white chili bean and it ma...
2,1,14299,Creamy White Chili,Barbara566,10,0,3,0,5,710,I have a very complicated white chicken chili ...
3,1,14299,Creamy White Chili,jeansch123,1,2,2,0,0,581,"In your introduction, you mentioned cream chee..."
4,1,14299,Creamy White Chili,camper77,10,1,7,0,0,820,Wonderful! I made this for a &#34;Chili/Stew&#...
...,...,...,...,...,...,...,...,...,...,...,...
18177,100,82745,Mamaw Emily’s Strawberry Cake,WhittierCA,1,0,0,0,5,100,This Strawberry Cake has been a family favorit...
18178,100,82745,Mamaw Emily’s Strawberry Cake,susieswan,1,0,0,0,5,100,<p>I received endless compliments on this cake...
18179,100,82745,Mamaw Emily’s Strawberry Cake,blajr,1,0,0,0,5,100,This cake was delicious and so moist! I didn&#...
18180,100,82745,Mamaw Emily’s Strawberry Cake,cafritz,1,0,0,0,5,100,I just made this too. It is wonderful. As fo...
18181,100,82745,Mamaw Emily’s Strawberry Cake,nopalito,1,0,1,0,5,193,"OMG, you must make this cake. I made it for my..."

In [105]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from gensim.models import Word2Vec

# Download necessary NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize preprocessing tools
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

# Define preprocessing function
def preprocess_text(text):
    if not isinstance(text, str):
        return ""
    text = re.sub(r'[^\w\s]', '', text.lower())  # Remove punctuation and convert to lowercase
    text = re.sub(r'\d+', '', text)  # Remove digits
    words = text.split()
    return ' '.join([lemmatizer.lemmatize(word) for word in words if word not in stop_words])

# Apply preprocessing to text column (adjust column name if different)
data['Cleaned_Review'] = data['text'].apply(preprocess_text)

# Tokenize for Word2Vec
tokenized_reviews = data['Cleaned_Review'].apply(lambda x: x.split())

# Train Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_reviews, vector_size=100, window=5, min_count=1, workers=4)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/huiyisang/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/huiyisang/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/huiyisang/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
/var/folders/hj/50ynckj97xq7d49_2_s66f100000gn/T/ipykernel_90388/3345681019.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Cleaned_Review'] = data['text'].apply(preprocess_text)

In [106]:
# Function to generate the vector for a single review
def get_review_vector(review, model, vector_size):
    """
    Generate the vector for a review by averaging word vectors.
    
    Parameters:
        review (str): The preprocessed review text.
        model (gensim.models.Word2Vec): The trained Word2Vec model.
        vector_size (int): Size of the word vectors.
    
    Returns:
        list: The averaged vector for the review as a list.
    """
    words = review.split()  # Tokenize the review
    word_vectors = [model.wv[word] for word in words if word in model.wv]
    if len(word_vectors) > 0:
        return np.mean(word_vectors, axis=0).tolist()  # Convert numpy array to list
    else:
        return [0.0] * vector_size  # Return a zero vector as a list if no words match

# Apply the function to each review and add a new column
vector_size = word2vec_model.vector_size  # Get vector size from the model
data['Review_Vector'] = data['Cleaned_Review'].apply(lambda x: get_review_vector(x, word2vec_model, vector_size))

/var/folders/hj/50ynckj97xq7d49_2_s66f100000gn/T/ipykernel_90388/2909804766.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Review_Vector'] = data['Cleaned_Review'].apply(lambda x: get_review_vector(x, word2vec_model, vector_size))

In [107]:
data

,recipe_number,recipe_code,recipe_name,user_name,user_reputation,reply_count,thumbs_up,thumbs_down,stars,best_score,text,Cleaned_Review,Review_Vector
0,1,14299,Creamy White Chili,Jeri326,1,0,0,0,5,527,"I tweaked it a little, removed onions because ...",tweaked little removed onion onion hater house...,"[0.042419105768203735, 0.13731247186660767, 0...."
1,1,14299,Creamy White Chili,Mark467,50,0,7,0,5,724,Bush used to have a white chili bean and it ma...,bush used white chili bean made recipe super s...,"[-0.0801309272646904, 0.32824960350990295, -0...."
2,1,14299,Creamy White Chili,Barbara566,10,0,3,0,5,710,I have a very complicated white chicken chili ...,complicated white chicken chili recipe made ye...,"[-0.0745932012796402, 0.17860424518585205, 0.0..."
3,1,14299,Creamy White Chili,jeansch123,1,2,2,0,0,581,"In your introduction, you mentioned cream chee...",introduction mentioned cream cheese none liste...,"[-0.0017485821153968573, -0.31456276774406433,..."
4,1,14299,Creamy White Chili,camper77,10,1,7,0,0,820,Wonderful! I made this for a &#34;Chili/Stew&#...,wonderful made chilistew night dinner church e...,"[-0.4228358864784241, 0.1858411431312561, -0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18177,100,82745,Mamaw Emily’s Strawberry Cake,WhittierCA,1,0,0,0,5,100,This Strawberry Cake has been a family favorit...,strawberry cake family favorite since past sev...,"[-0.5059157609939575, 0.6359168291091919, -0.2..."
18178,100,82745,Mamaw Emily’s Strawberry Cake,susieswan,1,0,0,0,5,100,<p>I received endless compliments on this cake...,pi received endless compliment cake used firme...,"[-0.27236151695251465, -0.0509437620639801, -0..."
18179,100,82745,Mamaw Emily’s Strawberry Cake,blajr,1,0,0,0,5,100,This cake was delicious and so moist! I didn&#...,cake delicious moist didnt need sugar called f...,"[-0.08041729032993317, 0.05896424502134323, -0..."
18180,100,82745,Mamaw Emily’s Strawberry Cake,cafritz,1,0,0,0,5,100,I just made this too. It is wonderful. As fo...,made wonderful frosting wish made thicker tad ...,"[-0.3331168591976166, -0.0677044615149498, -0...."
18181,100,82745,Mamaw Emily’s Strawberry Cake,nopalito,1,0,1,0,5,193,"OMG, you must make this cake. I made it for my...",omg must make cake made strawberrycrazy daught...,"[-0.287492960691452, -0.039966028183698654, -0..."

In [108]:
df1 = data.drop(columns=['text','Cleaned_Review'])

In [109]:
df1.dtypes

recipe_number       int64
recipe_code         int64
recipe_name        object
user_name          object
user_reputation     int64
reply_count         int64
thumbs_up           int64
thumbs_down         int64
stars               int64
best_score          int64
Review_Vector      object
dtype: object

In [110]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.utils import to_categorical

In [112]:
# Drop rows with invalid or missing 'Review_Vector'
df1 = df1.dropna(subset=['Review_Vector'])

# Convert 'Review_Vector' to NumPy array
X = df1[['best_score','Review_Vector']]
y = df1[['stars']]

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout

# Define the RNN architecture
model = Sequential([
    LSTM(64, input_shape=(X_train.shape[1], 1), return_sequences=False),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(y_train.shape[1], activation='softmax')  # Ensure output matches the number of classes
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=20, batch_size=32)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")

ValueError: Invalid dtype: object

In [ ]:
# Predict on test data
predictions = model.predict(X_test_reshaped)

# Convert predictions back to class labels
predicted_classes = np.argmax(predictions, axis=1) + 1  # Add 1 because classes are 1-5
actual_classes = np.argmax(y_test, axis=1) + 1

# Display predictions and actual values
for pred, actual in zip(predicted_classes[:10], actual_classes[:10]):
    print(f"Predicted: {pred}, Actual: {actual}")